version: '3'
services:
  db:
    image: quay.io/azavea/postgis:2.4-postgres10.3-slim
    volumes:
      - ./data/:/opt/data/
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "osm"
      POSTGRES_USER: "osm"
      POSTGRES_DB: "osm-stats"
      PGDATA: "/opt/data"
  osm-stat-server:
    image: quay.io/geotrellis/osm-stat-server:latest
    volumes:
      - ~/.aws:/root/.aws
    ports:
      - "8080:8080"
    links:
      - "db:database"
    build:
      context: docker/osm-stat-server
      dockerfile: Dockerfile
    environment:
      DB_DRIVER: "org.postgresql.Driver"
      DB_URL: "jdbc:postgresql://db:5432/osm-stats"
      DB_USER: "osm"
      DB_PASS: "osm"
      TILE_BUCKET: "geotrellis-test"
      TILE_PREFIX: "npz"
      TILE_SUFFIX: ".png"
      TILE_CHUNK_SIZE: 4096
    stdin_open: true
    tty: true

